config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :characters
  resources :items
  resources :locations
  resources :enemys
  resources :pages
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
	belongs_to :user
	has_many :items
	has_one :location
	has_one :fight_enemy



	validates :nickname, :character_class, presence: true
	validates :nickname, uniqueness: true
	validates :nickname, format: { with: /\A[a-zA-Z]+\z/,
	    		message: "only allows letters" }
	validates :nickname, length: { in: 3..16 }
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def set_avatar
    if self.avatar
      "/assets/#{self.character_class}.png"
    end
  end
end

app/models/enemy.rb
class Enemy < ApplicationRecord
after_create :find_num 

belongs_to :location
has_many :enemies

private 

def find_num
	update(num: location.enemies.count())
	update(boss: true)
	location.enemies.each{|enemy|
		if(enemy.boss && enemy.id != id)
			enemy.update(boss: false)
		end
	}
end
end

app/models/fight_enemy.rb
class FightEnemy < ApplicationRecord

	belongs_to :enemy
	belongs_to :character

	def fight
		enemy.update(hp: enemy.hp-character.damage)
	end

	def dead
		if(enemy.boss)
			character.update(fight_enemy_id: nil, location_id: nil , num: nil, exp: character.exp+5)
		else
			character.update(fight_enemy_id: nil, exp: character.exp+2)
		end

		if(character.exp >= 25)
			character.update(exp: 0)
			character.update(lvl: character.lvl+1)
			character.update(damage: character.damage+3)
			character.update(hp: character.hp+25)
		end

		if (enemy.lvl == 1)
			if (enemy.boss)
				enemy.update(hp: 100)
			else
				enemy.update(hp: 50)
			end
		end

		if (enemy.lvl == 5)
			if (enemy.boss)
				enemy.update(hp: 200)
			else
				enemy.update(hp: 100)
			end
		end

		if (enemy.lvl == 10)
			if (enemy.boss)
				enemy.update(hp: 400)
			else
				enemy.update(hp: 200)
			end
		end
		
		#@character.fight_enemy.deat
		delete
	end

end

app/models/item.rb
class Item < ApplicationRecord
	
end

app/models/location.rb
class Location < ApplicationRecord
	has_many :enemies
	#has_many :characters
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one :character
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :check_character


 private
  def check_character
  	if (user_signed_in?)
    	if (!current_user.character)
  			redirect_to new_character_path
  		end
  	end
  end

  
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_character, only: [:show, :edit, :update, :destroy]
  def index
    @characters = Character.all
  end

  def new
  	@character = Character.new
  end

  def create
    @character = current_user.build_character(character_params)
    if @character.character_class == "Warrior"
      @character.damage = 15
      @character.hp = 300
    end
    if @character.character_class == "Rogue"
      @character.damage = 19
      @character.hp = 250
    end
    if @character.character_class == "Mage"
      @character.damage = 23
      @character.hp = 200
    end
    if @character.save
      redirect_to character_path(current_user.character)
    else
      render 'new'
    end
  end

  def show

  end

  def edit
    
  end

  def update
  	if @character.update(character_params)
      redirect_to character_path(current_user.id)
    else
      render 'edit'
    end
  end

  def destroy
  	@character.destroy
    redirect_to root_path
  end

  def check_character
    
  end
 
private
  def character_params
    params.require(:character).permit(:user_id,:nickname,:character_class, :lvl, :avatar)
  end
  def find_character
    @character = Character.find_by(id:params[:id])
  end
end

app/controllers/enemys_controller.rb
class EnemysController < ApplicationController
  before_action :authenticate_user!
  before_action :find_enemy, only: %i[show,edit,update,destroy]
  def index
  	@enemys= Enemy.all
  end

  def new
  	@enemy=Enemy.new
  end

  def create
  	@enemy = Enemy.new(params_enemy)
  	if @enemy.save
  		redirect_to enemys_path
  	end
  end

  def edit; end

  def update; end

  def destroy; end

  private 

  def params_enemy
  	params.require(:enemy).permit(:name, :lvl, :hp, :damage, :num, :location_id, :boss)
  end

  def find_enemy
  	@enemy= Enemy.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
     before_action :find_item, only: [:show, :edit, :update, :destroy]
  def index
  	@items = Item.all
  end

  def new
  	@item = Item.new
  end
  def create
  	@item = current_user.items.build(item_params)
    if @item.save
      redirect_to root_path
    end
  end

  def show

  end

  def edit
  end
  def update
  	
  end

  def destroy
  	
  end
private
  def item_params
    params.require(:item).permit(:character_id, :name, :character_class, :rarity, :lvl)
  end
   def find_item
      @item = Item.find_by(id:params[:id])
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	before_action :authenticate_user!
	before_action :find_location, only: [:index , :show, :edit, :update, :destroy]
  
  def index
  	redirect_to location_path(current_user.character.location_id) if current_user.character.location_id
  	@locations=Location.all
  end

  def new
  	@location = Location.new
  end

  def create
  	@location = Location.new(location_params)
  	if @location.save
  		redirect_to locations_path
  	end
  end

  def show
  	find_character
  	if(@character.location_id)
  		redirect_to location_path(character.location_id) unless @character.location_id = @location.id 
  	else
  		@character.update(location_id: @location.id)
  	end
  	if(@character.fight_enemy_id)


      if (@character.fight_enemy.enemy.hp <= 0)
        @character.fight_enemy.dead
      else
        @character.fight_enemy.fight
      end
  		

  		if @character.fight_enemy.enemy.boss
        if @character.fight_enemy.enemy.hp <= 0
          @character.fight_enemy.dead
          flash[:notice] = "You WIN"
          redirect_to locations_path
        end
  			
  		end

  		#Якщо битва продовжується
  	else
  		#якщо битви нема 
  		if(@character.num)
  			@character.update(num: @character.num+1) 
  		else
  			@character.update(num: 1)
  		end
  		@enemy = Enemy.find_by(location_id: @location.id, num: @character.num)
  		@fight_enemy =@character.build_fight_enemy(enemy_id: @enemy.id) 
  		@fight_enemy.save
  		@character.update(fight_enemy_id: @fight_enemy.id)

  	end
  end

  private
  	def location_params
      	params.require(:location).permit(:bosse_id,:enemy_id,:name)
    end

    def find_location
    	@location = Location.find_by(id:params[:id])
  	end

  	def find_character
  		@character = current_user.character
  	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!
  def index
  	@character = Character.all
  	if (user_signed_in?)
      if (!current_user.character.nil?)
        redirect_to character_path(current_user.character)
      end
    end 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/enemys_helper.rb
module EnemysHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/characters/edit.html.erb
<h1>Change nickname</h1>

<%= form_for @character, url: {action: "update"} do |f| %>
<% if @character.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>
 
    <ul>
    <% @character.errors.full_messages.each do |msg| %>
      <li><%= msg %></li> 
    <% end %>
    </ul>
  </div>
<% end %>
<br>
<strong>nickname</strong><br>
<%= f.text_field :nickname %><br>
<br>


<%= f.submit "Save" %>
<% end %>

app/views/characters/index.html.erb
<h1>Characters#index</h1>
<p>Find me in app/views/characters/index.html.erb</p>

app/views/characters/new.html.erb
<h1>Create your character</h1>

<%= form_for @character, url: {action: "create"} do |f| %>

<% if @character.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>
 
    <ul>
    <% @character.errors.full_messages.each do |msg| %>
      <li><%= msg %></li> 
    <% end %>
    </ul>
  </div>
<% end %>

<br>
<h4><strong>Enter your nickname</strong><br></h4>
<%= f.text_field :nickname %><br>
<h4><strong>choose class</strong><br></h4> 

<%= f.collection_radio_buttons(:character_class,  [['Warrior', 'Warrior'] ,['Rogue', 'Rogue'], ['Mage', 'Mage']], :first, :last) do |b| %>
  <%= b.label { b.radio_button + image_tag('/assets/'+b.text+'.png') } %>
<% end %>
<br>
<br>
<%= f.submit "Create" %>
<% end %>

app/views/characters/show.html.erb
<h1>Your character</h1>

<%= image_tag @character.set_avatar %> <br>
<strong>Class: </strong> <%= @character.character_class %><br/>
<strong>Nickname: </strong><%= @character.nickname %><br/>
<strong>Lvl: </strong><%= @character.lvl %><br/>
<strong>Experience: </strong><%= @character.exp %><br/>
<strong>HealthPoint: </strong><%= @character.hp %><br/>
<strong>Damage: </strong><%= @character.damage %><br/>

<% if @character.user_id == current_user.id %>
<h5><%= link_to "Change nickname", edit_character_path(@character.id) %> | 
	<%= link_to "Delete", character_path(@character.id), method: :delete, data: {confirm: "are you sure?"} %><br/></h5>	
<% end %>

app/views/enemys/edit.html.erb
<h1>Enemys#edit</h1>
<p>Find me in app/views/enemys/edit.html.erb</p>

app/views/enemys/index.html.erb
<h1>Enemys#index</h1>
<p>Find me in app/views/enemys/index.html.erb</p>

app/views/enemys/new.html.erb
<h1>Enemys#new</h1>
<p>Find me in app/views/enemys/new.html.erb</p>

<%= form_for @enemy, url: {action: "create"} do |f| %>
<strong>name</strong><br>
<%= f.text_field :name %><br>
<strong>lvl</strong><br>
<%= f.text_field :lvl %><br>
<strong>hp</strong><br>
<%= f.text_field :hp %><br>
<strong>damage</strong><br>
<%= f.text_field :damage %><br>
<strong>location</strong>
<%= f.select :location_id  , Location.all.collect {|p| [ p.name, p.id ]}%> <br>

<%= f.submit "Create" %>
<% end %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

<%= form_for :item, url: items_path do |f| %>
<strong>name</strong><br>
<%= f.text_field :name %><br>
<strong>choose class</strong><br>
<%= f.radio_button :character_class, 'Warrior' %> Warrior<br />
<%= f.radio_button :character_class, 'Rogue' %> Rogue<br />
<%= f.radio_button :character_class, 'Mage' %> Mage<br />
<strong>choose rarity</strong><br>
<%= f.radio_button :rarity, 'arcane' %> arcane<br />
<%= f.radio_button :rarity, 'mythic' %> mythic<br />
<%= f.radio_button :rarity, 'legendary' %> legendary<br />
<%= f.radio_button :rarity, 'epic' %> epic<br />
<%= f.radio_button :rarity, 'rare' %> rare<br />
<%= f.radio_button :rarity, 'common' %> common<br />
<strong>lvl</strong><br>
<%= f.text_field :lvl %><br>
<%= f.submit "Create" %>
<% end %>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/layouts/_footer.html.erb
<p>Copyright 2018 by Kusha</p>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <%= link_to "Character", character_path(current_user.id) %> |
  <%= link_to "Map", locations_path  %> |
	<%= link_to "Rules", page_path(current_user.id)  %> | 
  <%= link_to "Logout",  destroy_user_session_path, method: :delete %>
<% else %>
   <%= link_to "Login", new_user_session_path %>
<% end %>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arcane</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render "layouts/header" %>

    <%- flash.each do |name, message| %>
      <p><i><%= "#{name}: #{message}" %></i></p>
    <% end %>

    <%= yield %>

    <hr>
    
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/locations/index.html.erb
<h1>Choose a location</h1>
<% if @locations == [] %>
    <p>nope</p>
<% else %>
    <% @locations.each do |l| %>
		<h3><strong><%= link_to l.name, location_path(l.id) %></strong></h3>
   		<hr>
    <% end %>
<% end %>

app/views/locations/new.html.erb
<h1>Locations#new</h1>
<p>Find me in app/views/locations/new.html.erb</p>
<%= form_for @location, url: {action: "create"} do |f| %>

<%= f.text_field :name %>
<%= f.submit "Create" %>
<% end %>

app/views/locations/show.html.erb
<h2><strong>Location name: </strong> <%= @location.name %> (<strong>List of enemys: <%= @location.enemies.collect{|enemy| enemy.name}.join(", ")%></strong>)</h2>
<h4><strong>Current enemy: <%= @character.fight_enemy.enemy.name %></strong></h4>
<% if @character.fight_enemy.enemy.boss %>
	<h4><strong>BOSS</strong></h4>
<% end %>
<h5><strong>Enemy damage: <%= @character.fight_enemy.enemy.damage %></strong></h5>
<h5><strong>Enemy health: <%= @character.fight_enemy.enemy.hp %></strong></h5>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<% if user_signed_in?%>
	<% if @characters == [] %>
		<p>No characters</p>
		<%= link_to  "Create new character", new_character_path %> <br>
		<%=  link_to  "Log out", destroy_user_session_path, method: :delete %><br/>
	<% else %>
		<%= link_to  "Create new character", new_character_path %>
		<hr>
		<% @character.each do | char | %> 
		<strong>nickname</strong><br>
		<%= char.nickname %><br/>
		<strong>class</strong><br>
		<%= char.character_class %><br/>
		<strong>lvl</strong><br>
		<%= char.lvl %><br/>
		<hr>
		<% end %>
		<%=  link_to  "Log out", destroy_user_session_path, method: :delete %><br/>
		<%=  link_to  "Create item", new_item_path%><br/>
		
	<% end %>
<% else %>
	<%=  link_to  "Log in", new_user_session_path %><br>
<%end%>

app/views/pages/show.html.erb
<h4>В кожного персонажа свої показники Damage i HeathPoint, що почати гру потрібно зайти в карту і обати локацію в якій хочете грати, локації відрізняються важкістю, на останній локації на першому рівні персонажа. За вбивство моба ви отримуєте 2 очки досвіду, за боса 5, щоб ваш рівень повисився потрібно зібрати 25 очків досвіду.</h4>